In [1]:
import pandas as pd
import numpy as np

In [6]:
print("hr")

hr

In [5]:
# 1. Create a Pandas Series containing the marks: 78, 85, 92, 67, 88

#     Display:

# 	Complete Series
# 	Values
# 	Index
# 	Data type
# 	Mean
# 	Maximum
# 	Minimum
marks = pd.Series([78, 85, 92, 67, 88])
print("Marks:", marks)
print("Values:", marks.values)
print("Index:", marks.index)
print("Data Type:", marks.dtype)
print("Mean:", marks.mean())
print("Maximum:", marks.max())
print("Minimum:", marks.min())

Marks: 0    78
1    85
2    92
3    67
4    88
dtype: int64
Values: [78 85 92 67 88]
Index: RangeIndex(start=0, stop=5, step=1)
Data Type: int64
Mean: 82.0
Maximum: 92
Minimum: 67

In [6]:
# 2. Create a Series containing:
 
#    	| Student | Marks |
# 	| ------- | ----: |
# 	| Asha    |    85 |
# 	| Ravi    |    78 |
# 	| Meena   |    92 |
# 	| Kiran   |    74 |
# 	| Arun    |    88 |
# 	Display the marks of Meena.
student_marks = pd.Series([85, 78, 92, 74, 88], index=['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun'])
print("Marks of Meena:", student_marks['Meena'])

Marks of Meena: 92

In [9]:
# 3. Create the following DataFrame:

# | Name  | Age | Department | Marks |
# | ----- | --: | ---------- | ----: |
# | Asha  |  22 | CSE        |    85 |
# | Ravi  |  23 | ECE        |    78 |
# | Meena |  21 | CSE        |    92 |
# | Kiran |  24 | ME         |    74 |
# | Arun  |  22 | ECE        |    88 |

# Display:

# 	Complete DataFrame
# 	First 3 rows
# 	Last 2 rows
# 	Shape
# 	Column names
# 	Data types
df=pd.DataFrame({
    'Name': ['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun'],
    'Age': [22, 23, 21, 24, 22],
    'Department': ['CSE', 'ECE', 'CSE', 'ME', 'ECE'],
    'Marks': [85, 78, 92, 74, 88]
})
print("Complete DataFrame:\n", df)
print("\nFirst 3 rows:\n", df.head(3))
print("\nLast 2 rows:\n", df.tail(2))
print("\nShape:", df.shape)
print("\nColumn names:", df.columns)
print("\nData types:\n", df.dtypes)

Complete DataFrame:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

First 3 rows:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Last 2 rows:
     Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

Shape: (5, 4)

Column names: Index(['Name', 'Age', 'Department', 'Marks'], dtype='str')

Data types:
 Name            str
Age           int64
Department      str
Marks         int64
dtype: object

In [10]:
# 4. Using the previous DataFrame, display:

# 	info()
# 	describe()
# 	Number of rows
# 	Number of columns
print("\nInfo:\n",df.info())
print("\nDescribe:\n",df.describe())
print("\nNo.of rows:", df.shape[0])
print("\nNo.of columns:", df.shape[1])

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Marks       5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

Info:
 None

Describe:
              Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

No.of rows: 5

No.of columns: 4

In [11]:
# 5. Using df, display:

# 	Name column
# 	Marks column
# 	Name and Marks together
print("\nName column:\n", df['Name'])
print("\nMarks column:\n", df['Marks'])
print("\nName and Marks together:\n", df[['Name', 'Marks']])

Name column:
 0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
Name: Name, dtype: str

Marks column:
 0    85
1    78
2    92
3    74
4    88
Name: Marks, dtype: int64

Name and Marks together:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [12]:
    # 6. Display:

    # 	First row using iloc
    # 	Third row using iloc
    # 	Rows 1 to 3
    # 	Name and Marks columns using loc
print("\n1st row using iloc:\n", df.iloc[0])
print("\n3rd row using iloc:\n", df.iloc[2])
print("\nRows 1 to 3:\n", df.iloc[1:4])
print("\nName and Marks columns using loc:\n", df.loc[:, ['Name', 'Marks']])

1st row using iloc:
 Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object

3rd row using iloc:
 Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object

Rows 1 to 3:
     Name  Age Department  Marks
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74

Name and Marks columns using loc:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [13]:
# 7. Find:

# 	Students scoring above 80.
# 	Students scoring between 75 and 90.
# 	Students belonging to CSE.
# 	CSE students scoring above 80.
print("Students scoring >80:\n",df[df['Marks']>80])
print("Students scoring between 75 and 90:\n",df[(df['Marks']>75) & (df['Marks']<90)])
print("Students belonging to CSE:\n",df[df['Department']=='CSE'])
print("CSE students scoring above 80:\n",df[(df['Department']=='CSE') & (df['Marks']>80)])

Students scoring >80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88
Students scoring between 75 and 90:
    Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88
Students belonging to CSE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
CSE students scoring above 80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

In [14]:
# 8. Display students belonging to either CSE or ECE.
print("Students belonging to either CSE or ECE:\n", df[(df['Department']=='CSE') | (df['Department']=='ECE')])

Students belonging to either CSE or ECE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
4   Arun   22        ECE     88

In [ ]:
# # 9. Add a new column called Result. Students scoring 75 or above should receive "Pass", otherwise "Fail".
df['Result']=df['Marks'].apply(lambda x: 'Pass' if x>=75 else 'Fail')
df

    Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

In [20]:
# 10. Assign grades according to:

# 	| Marks | Grade |
# 	| ----: | ----- |
# 	|  ≥ 90 | A     |
# 	|  ≥ 80 | B     |
# 	|  ≥ 70 | C     |
# 	|  < 70 | D     |
df['Grade'] = pd.cut(df['Marks'], bins=[0, 70, 80, 90, 100], labels=['D', 'C', 'B', 'A'], right=False)
df

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

In [25]:
# 11. Sort students:

# 	By marks in ascending order.
# 	By marks in descending order.
# 	By Department and then Marks.
df1=df.sort_values(by='Marks',ascending=True)
df2=df.sort_values(by='Marks',ascending=False)
df3=df.sort_values(by=['Department', 'Marks'],ascending=[True, True])
print("\nSorted by marks in ascending order:\n", df1)
print("\nSorted by marks in descending order:\n", df2)
print("\nSorted by Department and then Marks:\n", df3)

Sorted by marks in ascending order:
     Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A

Sorted by marks in descending order:
     Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C

Sorted by Department and then Marks:
     Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

In [3]:
# 12. Consider:

# data = {
#     "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
#     "Age": [22, 23, np.nan, 24, 22],
#     "Marks": [85, np.nan, 92, 74, 88]
# }
# students = pd.DataFrame(data)
# Find:
# Missing values
# Number of missing values in each column
# Rows containing missing values
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}
students = pd.DataFrame(data)
print("\nMissing values:\n", students.isnull())
print("\nNumber of missing values in each column:\n", students.isnull().sum())
print("\nRows containing missing values:\n", students[students.isnull().any(axis=1)])

NameError: name 'np' is not defined

In [2]:
# 13. Replace:

# 	Missing Age with average Age
# 	Missing Marks with average Marks
students['Age'] = students['Age'].fillna(students['Age'].mean())
students['Marks'] = students['Marks'].fillna(students['Marks'].mean())
students

NameError: name 'students' is not defined

In [ ]:
#14. Remove rows containing missing values.
print("\nMissing values:\n", students.isnull())