In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

data={
    "Study Hours_day":[2, 3, 4, 5,6,7,8,9],
    "Attendeance":[60,65,70,75,80,85,90,95],
    "Assignment_Score":[50,55,58,65,70,74,80,88],
    "Final_Marks":[42,48,54,61,67,73,81,89]
}

In [2]:
df=pd.DataFrame(data)
df['Study_Hours_week'] = df['Study Hours_day'] * 7
print(df)

   Study Hours_day  Attendeance  Assignment_Score  Final_Marks  \
0                2           60                50           42
1                3           65                55           48
2                4           70                58           54
3                5           75                65           61
4                6           80                70           67
5                7           85                74           73
6                8           90                80           81
7                9           95                88           89

   Study_Hours_week
0                14
1                21
2                28
3                35
4                42
5                49
6                56
7                63

In [3]:
x=df[["Study Hours_day", "Attendeance", "Assignment_Score", "Study_Hours_week"]]
y=df["Final_Marks"]

In [4]:
x

   Study Hours_day  Attendeance  Assignment_Score  Study_Hours_week
0                2           60                50                14
1                3           65                55                21
2                4           70                58                28
3                5           75                65                35
4                6           80                70                42
5                7           85                74                49
6                8           90                80                56
7                9           95                88                63

In [5]:
y

0    42
1    48
2    54
3    61
4    67
5    73
6    81
7    89
Name: Final_Marks, dtype: int64

In [10]:
model = LinearRegression()
model.fit(x, y)
print("Intercept:", model.intercept_)

Intercept: -6.852852852852834

In [11]:
coefficient_table=pd.DataFrame({'Feature': x.columns, 'Coefficient': model.coef_})

In [12]:
coefficient_table

            Feature  Coefficient
0   Study Hours_day     0.045556
1       Attendeance     0.227778
2  Assignment_Score     0.608108
3  Study_Hours_week     0.318889

In [15]:
new_student=pd.DataFrame({
    "Study Hours_day":[6],
    "Attendeance":[82],
    "Assignment_Score":[72],
    "Study_Hours_week":[42]
})
 
prediction = model.predict(new_student)
print("Predicted Final Marks for the new student:", prediction[0])

Predicted Final Marks for the new student: 69.27537537537538